import { useEffect, useState } from "react";
import Head from "next/head";
// import axios from "axios";
import CoinGecko from "coingecko-api";
const coinGeckoClient = new CoinGecko();
import styles from "../styles/Home.module.css";
import Menu from "../components/Menu";
// import Base from "../components/Base";
import BlockCrypto from "../components/BlockCrypto";

export default function Home(props) {
  const { data } = props.result;
  console.log(data);
  // const [coins, setCoins] = useState([]);

  // useEffect(() => {
  //   axios
  //     .get(
  //       "https://api.coingecko.com/api/v3/coins/markets?vs_currency=brl&order=market_cap_desc&per_page=250&page=1&sparkline=false"
  //     )
  //     .then((res) => {
  //       setCoins(res.data);
  //     })
  //     .catch((error) => alert("You error"));
  // }, []);

  // console.log(coins);

  return (
    <div className={styles.container}>
      <Head>
        <title>CoinCalc</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className={styles.content}>
        <Menu />
        <div className={styles.base}>
          <div className={styles.headerbar}>
            {data.map((coin) => (
              <BlockCrypto
                key={coin.id}
                name={coin.name}
                symbol={coin.symbol}
                currentprice={coin.currentprice}
                image={coin.image}
              />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const params = {
    order: CoinGecko.ORDER.MARKET_CAP_DESC,
  };
  const result = await coinGeckoClient.coins.markets({ params });
  return {
    props: {
      result,
    },
  };
}
